### ISSUE TITLE
use of name in pypi

### ISSUE THREAD

**Issue by jrollins** [graysonhead/arx#2]
Hello. I also have an active project named [`arx`](https://git.ligo.org/jameson.rollins/arx), and I was hoping to use that name in pypi.  Is this project still active?  If not, would you be open to releasing the name so that I could use it for my project?  Thanks in advance for the consideration.

**Comment by graysonhead** [comment]
Hey there,

I'd be happy to release it, but I'm very busy for the next few days and not
sure when I'll be able to get on my personal computer to hit the
button.  I'll hit the button next chance I get. Feel free to poke me in a
few days if I forget.

Regards,
Grayson Head

**Comment by jrollins** [comment]
Great!  Thanks so much Grayson!

**Comment by jrollins** [comment]
Hi @graysonhead, I opened up an official pypi name transfer request: https://github.com/pypa/pypi-support/issues/1834.  I couldn't figure out how to reference you directly in the issue.  Please let me know if you notice any issues.  Thanks again!

**Comment by jrollins** [comment]
I was following the instructions here: https://peps.python.org/pep-0541/#how-to-request-a-name-transfer

**Comment by jrollins** [comment]
Hi @graysonhead, ping on this?

**Comment by jrollins** [comment]
@graysonhead Thank you very much for release arx on pypi.  I very much appreciate it.
